CREATE DATABASE Core;

CREATE TABLE usuarios (
    id_usuario SERIAL PRIMARY KEY,
    nombre_usuario VARCHAR(100) NOT NULL,
    correo_usuario VARCHAR(100) UNIQUE NOT NULL,
    contrasena_usuario VARCHAR(255) NOT NULL,
    rol_usuario VARCHAR(50) NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_ultima_actividad TIMESTAMP,
    activo BOOLEAN DEFAULT TRUE
);


/* Inventory table */
CREATE TABLE botonera (
    id_btn        integer,
    codigo_btn      character varying(100),
    rut_cor       character varying(20),
    fecha_btn       timestamp without time zone,
    oid      integer,
);

CREATE TABLE core (
    rut_cor        character varying(20),
    nombre_cor      character varying(100),
    oid      integer not null generated by default,
);

CREATE TABLE ordenanza (
    id_ord        integer,
    codigo_ord     character varying(100),
    nombre_ord      character varying(1000),
    fecha_ord      date,
    umbral_ord      integer,
    aprobado_ord     boolean,
    segundos_ord      integer,
    en_votacion_ord      boolean,
    botoneras_totales_ord      integer,
    botoneras_vivas_ord      integer,
    oid      integer,
);

CREATE TABLE votacion (
    id_ord INTEGER NOT NULL,
    id_btn INTEGER NOT NULL,
    rut_cor CHARACTER VARYING(20),
    aprobado_vot BOOLEAN,
    fecha_vot TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    oid VARCHAR(100),
    PRIMARY KEY (id_ord, id_btn),
);

/*borra y  crear*/
DROP TABLE votacion;

CREATE TABLE votacion (
    id_votacion SERIAL PRIMARY KEY,
    id_ord INTEGER NOT NULL,
    id_btn INTEGER NOT NULL,
    rut_cor CHARACTER VARYING(20),
    aprobado_vot BOOLEAN,
    fecha_vot TIMESTAMP WITHOUT TIME ZONE,
    oid VARCHAR(100),
    FOREIGN KEY (id_ord) REFERENCES ordenanza(id_ord),
    FOREIGN KEY (id_btn) REFERENCES botonera(id_btn),
    FOREIGN KEY (rut_cor) REFERENCES core(rut_cor)
);

/*
psql -h [host] -U [usuario] -d [base_de_datos]
psql -h localhost -U postgres -d information_schema
psql -h database-core.c9i6cmoc8uba.us-east-2.rds.amazonaws.com -U postgres -d database-core
*/





